FROM ubuntu:bionic

VOLUME /mbdata
WORKDIR /mbdata

RUN apt-get update && \
    apt-get install -y curl wget gnupg2 && \
    echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/postgresql.list && \
    curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y \
      python3 \
      python3-dev \
      python3-pip \
      libpq-dev \
      gcc git vim virtualenv

ENTRYPOINT ["/bin/bash"]
