[project]
name = "mbdata"
description = "MusicBrainz Database Tools"
readme = "README.rst"
authors = [
    { name = "MetaBrainz Foundation", email = "support@metabrainz.org"},
    { name = "Lukáš Lalinský", email = "<lalinsky@gmail.com>"},
]
license = "MIT"
dynamic = ["version"]

[tool.poetry]
version = "0.0.0"

[tool.poetry.dependencies]
python = "^3.10"
SQLAlchemy = {version = "^1.4.29", optional = true}
lxml = {version = "^6.1.0", optional = true}
six = "^1.16.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.0"
psycopg2 = "^2.9.9"
sqlparse = "^0.6.0"
pytest = "^7.2.0"
mypy = "^0.991"
types-six = "^1.16.21"
types-psycopg2 = "^2.9.21"

[tool.poetry.extras]
search = ["lxml"]
models = ["SQLAlchemy"]

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
