name: Build Docker Image

on:
  push:
    branches:
      - main
      - master
      - build-docker-image

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push mbslave image
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile.mbslave
